### ISSUE TITLE
Not all data points captured

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/CellMapper-Android-App#92]
* CellMapper: App Version: 5.1.2
* Phone Model: Google Nexus 5X
* Language: en

I've taken a number of walks, where cellmapper was on the entire time, and showing towers, with good GPS.  In some cases it's a walk where there is only a single tower (no handoff).  When I see the plots later in the map, there are often long gaps.  Sometimes only half the points that should have been recorded show up.

I know cellmapper stops recording for a few seconds when there's a handoff.  I often lock the phone to a single band with *#*#4636#*#* to reduce cell handoff.  Even with that, I see big gaps in collected data.

**Comment by brycenesbitt** [comment]
For example.  I drove from Interstate 80 to "Lake Valley Reservoir" recording LTE
data, then switched to recording CDMA data for the return trip.  The LTE data processed just fine.  All but two data points of the CDMA data seems missing:

![cellmapper lte](https://user-images.githubusercontent.com/1294423/29446749-ad58668e-83a2-11e7-8ca3-7cf16e77969b.png)
![cellmapper cmda](https://user-images.githubusercontent.com/1294423/29446750-ad58fe82-83a2-11e7-9d53-662f81ad3aa6.png)

During the recording, the GPS was fine, signal strength fine, and data points were collected according to the app.

See the two little dots on the CDMA map?  That's all that made it.

**Comment by zivan56** [comment]
Can you enable CSV output and verify it logs the data points in there?

**Comment by brycenesbitt** [comment]
This data is gone, so no.

**Comment by zivan56** [comment]
It will log it once its turned on.

**Comment by brycenesbitt** [comment]
During the above trip, recording was on.  The App was on "show cells". The recording light was green, the GPS light was green, the account light was green.

**Comment by zivan56** [comment]
CellMapper doesn't pause recording until you pause it.  Either data is not getting updated from the RIL or it is invalid.

**Comment by brycenesbitt** [comment]
If "data is invalid", then cellmaper is not indicating this.  Could something in the UI turn green or red, depending if valid data is collected?

**Comment by Bryan48765** [comment]
SM-A510FD, marshmallow, old api, 57b194c07f8ea90b7a8386a2cae7be496e117a2761dc306312efe420c8ef67f2 sha256.
Airplane mode, rat change to unknown?, band change (RIL service mode) causes the app to stop adding points for 2 minutes. After a GPS and recording state restart, no change. After restarting the app, points haven't been added but there's no need to wait 2 minutes for it to resume recording. The RSSI and RSCP is updating automatically, and working fine, up to -51.
This is in the logcat:
Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
System.err: 	at cellmapper.net.cellmapper.p$6.run(Unknown Source)
System.err: 	at android.app.Activity.runOnUiThread(Activity.java:6050)
System.err: 	at cellmapper.net.cellmapper.p.update(Unknown Source)
System.err: 	at cellmapper.net.cellmapper.p.onAttach(Unknown Source)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
System.err: 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(Unknown Source)
System.err: 	at android.support.v4.app.FragmentTransition.calculateFragments(Unknown Source)
System.err: 	at android.support.v4.app.FragmentTransition.startTransitions(Unknown Source)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source)
System.err: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(Unknown Source)
System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source)
System.err: 	at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7325)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Will edit if I find something else.
